<a href="https://colab.research.google.com/github/arpitpatelsitapur/my-py-torch-journey/blob/main/pytorch_tensor_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.8.0+cu126'

In [ ]:
torch.cuda.is_available()

True

In [ ]:
torch.cuda.get_device_name()

'Tesla T4'

## **Creating Tensors**

In [ ]:
torch.empty(2,3)

tensor([[-2.0253e-09,  4.4648e-41,  1.3679e-17],
        [ 0.0000e+00,  1.4013e-45,  0.0000e+00]])

In [ ]:
torch.rand(2,3)

tensor([[0.8427, 0.5926, 0.8286],
        [0.5981, 0.5735, 0.7575]])

In [ ]:
torch.randint(low=0, high=2, size=(3,3))

tensor([[0, 1, 1],
        [1, 1, 0],
        [1, 1, 1]])

In [ ]:
torch.manual_seed(2)

In [ ]:
torch.tensor([1,2,3,4])

tensor([1, 2, 3, 4])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [ ]:
torch.eye(3).shape

torch.Size([3, 3])

## **Dimensions of tensors**
from the rightmost argument:<br>
```torch.ones(a, b, c, d, e, f, ...)```
- last dim = columns
- second last = rows
- third last = depth (stack of matrices → cube)
- fourth last = blocks (collection of cubes)
- fifth last = blocks of blocks …
- and so on

In [ ]:
torch.empty(1)

tensor([2.9301e+12])

In [ ]:
torch.empty(1,2)

tensor([[9.3024e-06, 0.0000e+00]])

In [ ]:
torch.empty(2,1)

tensor([[2.9301e+12],
        [4.3837e-41]])

In [ ]:
torch.zeros(1,2,3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
torch.zeros(2,3,1)

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [ ]:
torch.zeros(3,2,1)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]])

In [ ]:
torch.ones(1,2,3,4)

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [ ]:
torch.ones(2,3,4,1)

tensor([[[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]],


        [[[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]],

         [[1.],
          [1.],
          [1.],
          [1.]]]])

In [ ]:
torch.ones(3,4,1,2)

tensor([[[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]],


        [[[1., 1.]],

         [[1., 1.]],

         [[1., 1.]],

         [[1., 1.]]]])

In [ ]:
torch.ones(1,2,3,4,5)

tensor([[[[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]],


         [[[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]],

          [[1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.],
           [1., 1., 1., 1., 1.]]]]])

## **Tensor with same shape as given tensor**

In [ ]:
x=torch.empty(2,3)
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

## **Tensor datatype**

In [ ]:
x.dtype

torch.float32

In [ ]:
torch.ones(2,3, dtype=torch.int)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
torch.rand(2,3, dtype=torch.float64)

tensor([[0.9176, 0.0969, 0.7088],
        [0.5403, 0.9133, 0.5257]], dtype=torch.float64)

In [ ]:
x.to(torch.int)

tensor([[0, 0, 0],
        [0, 1, 0]], dtype=torch.int32)

In [ ]:
x.to(torch.double)

tensor([[1.4530e-17, 0.0000e+00, 1.3601e-17],
        [0.0000e+00, 1.0000e+00, 0.0000e+00]], dtype=torch.float64)

## **Mathematical operations**

In [ ]:
a=torch.ones(2,3)
b=torch.rand(2,3)

In [ ]:
a+1

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
b

tensor([[0.3901, 0.9088, 0.5334],
        [0.7073, 0.7116, 0.2050]])

In [ ]:
b+1

tensor([[1.3901, 1.9088, 1.5334],
        [1.7073, 1.7116, 1.2050]])

In [ ]:
a+b

tensor([[1.3901, 1.9088, 1.5334],
        [1.7073, 1.7116, 1.2050]])

In [ ]:
a.add_(b)

tensor([[1.3901, 1.9088, 1.5334],
        [1.7073, 1.7116, 1.2050]])

In [ ]:
a

tensor([[1.3901, 1.9088, 1.5334],
        [1.7073, 1.7116, 1.2050]])

In [ ]:
torch.abs(a)

tensor([[1.3901, 1.9088, 1.5334],
        [1.7073, 1.7116, 1.2050]])

In [ ]:
torch.neg(a)

tensor([[-1.3901, -1.9088, -1.5334],
        [-1.7073, -1.7116, -1.2050]])

In [ ]:
torch.round(a)

tensor([[1., 2., 2.],
        [2., 2., 1.]])

In [ ]:
torch.ceil(a)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [ ]:
torch.floor(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.clamp(a, min=0.5, max=1.5)

tensor([[1.3901, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.2050]])

In [ ]:
x=torch.ones(2,2)
torch.sum(x)

tensor(4.)

In [ ]:
torch.sum(x, dim=0) #column

tensor([2., 2.])

In [ ]:
torch.mean(x)

tensor(1.)

In [ ]:
torch.mean(x, dim=0)

tensor([1., 1.])

In [ ]:
torch.median(x)

tensor(1.)

In [ ]:
torch.max(x)

tensor(1.)

In [ ]:
torch.min(x)

tensor(1.)

In [ ]:
torch.prod(x)

tensor(1.)

In [ ]:
torch.std(x)

tensor(0.)

In [ ]:
torch.var(x)

tensor(0.)

In [ ]:
torch.argmax(x)

tensor(0)

In [ ]:
torch.argmin(x)

tensor(0)

## **Matrix Operations**

In [ ]:
a=torch.ones(2,3)
b=torch.rand(3,2)

In [ ]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
b

tensor([[0.3078, 0.9809],
        [0.0103, 0.4660],
        [0.4604, 0.8547]])

In [ ]:
torch.matmul(a,b)

tensor([[0.7784, 2.3016],
        [0.7784, 2.3016]])

In [ ]:
torch.dot(torch.tensor([1,2,3]),torch.tensor([3,4,5]))

tensor(26)

In [ ]:
torch.transpose(a,0,1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
torch.det(torch.ones(3,3))

tensor(0.)

In [ ]:
torch.inverse(torch.rand(3,3))

tensor([[ -3.6004,  12.4498,  -2.4072],
        [  5.0402, -10.4626,   0.4706],
        [ -1.1652,   2.0498,   1.6638]])

## **Special functions**

In [ ]:
x=torch.linspace(1,10,10)
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.log(x)

tensor([0.0000, 0.6931, 1.0986, 1.3863, 1.6094, 1.7918, 1.9459, 2.0794, 2.1972,
        2.3026])

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02, 4.0343e+02,
        1.0966e+03, 2.9810e+03, 8.1031e+03, 2.2026e+04])

In [ ]:
torch.sqrt(x)

tensor([1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284, 3.0000,
        3.1623])

In [ ]:
torch.sigmoid(x)

tensor([0.7311, 0.8808, 0.9526, 0.9820, 0.9933, 0.9975, 0.9991, 0.9997, 0.9999,
        1.0000])

In [ ]:
torch.softmax(x,dim=0)

tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])

In [ ]:
torch.relu(x)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.sin(x)

tensor([ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,  0.9894,
         0.4121, -0.5440])

## **In-place Operations**

In [ ]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
x.add_(1)

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

## **Copying a Tensor**

In [ ]:
y=x # aliasing- changes in x will affect in y

In [ ]:
x.add_(1)

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
y

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
z=x.clone()
z

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x.add_(1)

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])

In [ ]:
z

tensor([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

## **using GPU for tensor operations**

In [ ]:
device=torch.device("cuda")

In [ ]:
a=torch.rand((2,3),device=device)

In [ ]:
x.to(device)

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.], device='cuda:0')

## **Reshaping Tensors**

In [ ]:
x.shape

torch.Size([10])

In [ ]:
x.reshape(2,5)

tensor([[ 4.,  5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12., 13.]])

In [ ]:
x.unsqueeze(0)

tensor([[ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.]])

In [ ]:
x.squeeze(-1)

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])

## **Numpy Arr to Tensor**

In [ ]:
y=x.numpy()
y

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.], dtype=float32)

In [ ]:
torch.from_numpy(y)

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])